FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine
LABEL version="1.0" maintainer="Erickson Lima"
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "CRUDApi.dll"]